import Footbar from "@/components/footbar";
import Navbar from "@/components/navbar";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { getTranslations } from "next-intl/server";
import { Exo, Instrument_Serif } from "next/font/google";
import { notFound } from "next/navigation";
import "../globals.css";

const exo_sans = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
});

const instrument_serif = Instrument_Serif({
  variable: "--font-instrument",
  subsets: ["latin"],
  weight: "400",
  style: "italic"
});

/* export const metadata: Metadata = {
  title: {
    default: "67 Design & Build – L’excellence du génie civil et du design architectural au Cameroun",
    template: "%s - 67 Design & Build"
  },
  description: "Generated by create next app",
}; */

export async function generateMetadata(params: Promise<{locale: string}>):Promise<Metadata>{
  const {locale} = await params;
  const t = await getTranslations({locale: locale, namespace: "SEO"});
  return {
  title: {
    default: t("home_title"),
    template: "%s - 67 Design & Build"
  },
  description: t("home_description"),
}
}

type Props = {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
};

export default async function LocaleLayout({children, params}: Props) {
    // Ensure that the incoming `locale` is valid
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body
        className={`${exo_sans.variable} ${instrument_serif.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <Navbar/>
          {children}
          <Footbar/>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
